services:
  - type: web
    name: scientific-journal-api
    runtime: node
    rootDir: apps/backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromDatabase:
          name: scientific-journal-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
